# Generated by Django 4.2.10 on 2024-02-17 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_avatar_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('prn_number', models.CharField(max_length=10, verbose_name='PRN Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255, verbose_name='Community Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('members', models.ManyToManyField(related_name='communities', related_query_name='community', to='users.member')),
            ],
            options={
                'verbose_name': 'community',
                'verbose_name_plural': 'communities',
                'ordering': ['name'],
            },
        ),
    ]
